// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnMWc7bcMhkdteSddDuTPibg1f5RCT0g',
    appId: '1:863657555780:web:bf8d1ac0ff242c80ed4911',
    messagingSenderId: '863657555780',
    projectId: 'she-sos-31880',
    authDomain: 'she-sos-31880.firebaseapp.com',
    storageBucket: 'she-sos-31880.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg8fWuhkUYS8Ze3t5uYB6XpPlBCPqIvKc',
    appId: '1:863657555780:android:d38629ffcf607232ed4911',
    messagingSenderId: '863657555780',
    projectId: 'she-sos-31880',
    storageBucket: 'she-sos-31880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUSJjOEj_G-qDBeF5Z5QkBmKfUDu_694c',
    appId: '1:863657555780:ios:dc912f3c2219ff58ed4911',
    messagingSenderId: '863657555780',
    projectId: 'she-sos-31880',
    storageBucket: 'she-sos-31880.firebasestorage.app',
    androidClientId: '863657555780-bnu77f6q3b9tab8tef2l776qqnq7p3ad.apps.googleusercontent.com',
    iosClientId: '863657555780-2i97v4csubqiji31fq5mrgukt06rm96e.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheSos',
  );

}